### ISSUE TITLE
Discussion about RESTFul API Design

### ISSUE THREAD

**Issue by brickgao** [TheSophon/sophon#1]
We have six parts to be done in this back-end project:
- Control SSH permission
- Get status of all hosts
- Get status of all service
- Account modules, support login / logout
- Auto-Deploying applications for developers
- Simple Docker control center and auto-deploying applications by using `dockerfile`

Okay, let's discuss them in this issue and update the result to wiki.

Sub-issues:

- [x] #2 Discussion about API for controlling SSH permission
- [x] #4 Discussion about API for account

**Comment by brickgao** [comment]
Here are some references for us to design:
- http://www.ruanyifeng.com/blog/2011/09/restful.html
- http://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api
- http://blog.jobbole.com/41233/

Also have a look at GitHub API or other API.

**Comment by gracegreat1** [comment]
Gocha.
