### ISSUE TITLE
Implement function to get the status of top 5 process on single host

### ISSUE THREAD

**Issue by brickgao** [TheSophon/sophon#36]
Function looks like:

```python
def get_host_process_status(ip):
    pass
```

return:

```python
[
    {
        "PID": 123,
        "User": "root",
        "Memory Usage": 0.0,
        "CPU Usage": 0.0,
        "Time": "0:01.82",
        "Command": "sample"
    },
    ...
]
```

**Comment by DevilBin** [comment]
What's the mean of "1"? I get a ip list?

**Comment by brickgao** [comment]
Top 5 process

2016-03-03 23:12 GMT+08:00 Haoyu Li <notifications@github.com>:

> What's the mean of "1"? I get a ip list?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TheSophon/sophon/issues/36#issuecomment-191806812>.
>



-- 
Regards,
Xiongzhi Gao,
School of Software Engineering of the University of Science and Technology
of China
